#!/bin/sh

SESSION=dropdown

# if the session is already running, just attach to it.
if tmux has-session -t $SESSION; then
  echo "Session $SESSION already exists. Attaching."
  sleep 1
  tmux -2 attach -t $SESSION
  exit 0;
fi

# create a new session, named $SESSION, and detach from it
tmux -2 new-session -d -s $SESSION

# Now populate the session with the windows you use every day
tmux set-option -g base-index 1
tmux set-window-option -t $SESSION -g automatic-rename off
tmux set-window-option -g pane-base-index 1

tmux new-window -t $SESSION:0 -k -n cruft
tmux split-window -h -p 50
tmux send-keys -t ${window}.1 'clear' Enter
tmux send-keys -t ${window}.1 'gcalcli agenda' Enter
tmux send-keys -t ${window}.2 'clear' Enter

tmux new-window -t $SESSION:1 -k -n mail
tmux send-keys -t ${window}.1 'neomutt' Enter

tmux new-window -t $SESSION:2 -k -n irc
tmux send-keys -t ${window}.1 'tiny' Enter

tmux new-window -t $SESSION:3 -k -n music
tmux send-keys -t ${window}.1 'ncmpcpp' Enter

tmux set-window-option -t $SESSION:0 automatic-rename off

# all done. select starting window and get to work
tmux select-window -t $SESSION:2
tmux -2 attach -t $SESSION
