#!/usr/bin/env bash

cd ~ || exit 1
SESSION=floating

# if the session is already running, just attach to it.
tmux has-session -t $SESSION
if [ $? -eq 0 ]; then
  echo "Session $SESSION already exists. Attaching."
  sleep 1
  tmux -2 attach -t $SESSION
  exit 0;
fi

# create a new session, named $SESSION, and detach from it
tmux -2 new-session -d -s $SESSION

# Now populate the session with the windows you use every day
tmux set-option -g base-index 1
tmux set-window-option -t $SESSION -g automatic-rename off
tmux set-window-option -g pane-base-index 1

tmux split-window -v -p 50
tmux select-pane -t 1
tmux split-window -h -p 80
tmux select-pane -t 1
tmux split-window -v -p 50
tmux select-pane -t 4
tmux split-window -v -p 10

tmux send-keys -t ${window}.1 'traffic' Enter
tmux send-keys -t ${window}.2 'cd ~/Documents/Projects/projects/gourcer' Enter
tmux send-keys -t ${window}.2 'clear' Enter
tmux send-keys -t ${window}.3 'taskwatch +work or pri:H' Enter
tmux send-keys -t ${window}.4 'echo four' Enter

tmux set-window-option -t $SESSION:0 automatic-rename off

# # all done. select starting window and get to work
tmux select-window -t $SESSION:0
tmux -2 attach -t $SESSION
