#!/bin/bash

cd ~/Documents/Projects/work/saama/kqrunner || return
SESSION=kqrunner

# if the session is already running, just attach to it.
tmux has-session -t $SESSION
if [ $? -eq 0 ]; then
  echo "Session $SESSION already exists. Attaching."
  sleep 1
  tmux -2 attach -t $SESSION
  exit 0;
fi

# create a new session, named $SESSION, and detach from it
tmux -2 new-session -d -s $SESSION

# Now populate the session with the windows you use every day
tmux set-option -g base-index 1
tmux set-window-option -t $SESSION -g automatic-rename off
tmux set-window-option -g pane-base-index 1

tmux new-window -t $SESSION:0 -k -n ide
tmux split-window -v -p 10
tmux select-pane -t 2
tmux split-window -h -p 50
tmux select-pane -t 3
tmux split-window -h -p 10
tmux select-pane -t 4
tmux split-window -h -p 50
tmux select-pane -t 5
tmux split-window -h -p 50

tmux send-keys -t ${window}.1 'vim' Enter
tmux send-keys -t ${window}.2 'watch kubectl get jobs' Enter
tmux send-keys -t ${window}.3 'start' Enter
tmux send-keys -t ${window}.4 'cd test && clear' Enter
tmux send-keys -t ${window}.4 'loop 10 python3 testjob.py'
tmux send-keys -t ${window}.5 'kubectl port-forward redis-57fc67768d-jthbq 7000:6379' Enter

tmux new-window -t $SESSION:1 -k -n cruft
tmux send-keys -t ${window}.1 'clear && git status' Enter

tmux set-window-option -t $SESSION:0 automatic-rename off

# all done. select starting window and get to work
tmux select-window -t $SESSION:0
tmux -2 attach -t $SESSION
