#!/bin/sh

imagepreview() {
    chafa --fill=block --symbols=block -c 256 -s 80x"$2" "$1"
}

videopreview() {
    set -e
    ffmpeg -ss 00:00:10 -i "$1" -vframes 1 -q:v 2 /tmp/videopreview.jpg
    imagepreview /tmp/videopreview.jpg "$2"
    rm /tmp/videopreview.jpg
    set +e
}

audiopreview() {
    ffmpeg -i "$1" 2>&1 | grep Duration | tr ',' '\n' | sed 's/^\ *//'
}

pdfpreview() {
    # probably try out pdftotext
    pdftohtml "$1" -i -f 1 -l 3 -stdout >/tmp/pdfpage.html
    w3m /tmp/pdfpage.html -dump
    rm /tmp/pdfpage.html
}

everythingelse() {
    if file --mime "$1" | grep 'charset=binary'; then
        MIMETYPE="$(file --mime ade.sketch | cut -d' ' -f2)"
        if echo "$MIMETYPE" | grep 'application/zip';then
            unzip -l "$1"    
        else
            file -b "$1"
        fi
    else
        bat --color=always --theme=base16 -p "$1" || cat "$1" || file "$1"
    fi
}

sketchpreview(){
    unzip "$1" "previews/preview.png" -d /tmp/sketch_preview >/dev/null 2>/dev/null
    imagepreview "/tmp/sketch_preview/previews/preview.png" "$2"
    rm -rf /tmp/sketch_preview
}

case "$1" in
*.tar*) tar tf "$1" ;;
*.zip) unzip -l "$1" ;;
*.rar) unrar l "$1" || file "$1" ;;
*.7z) 7z l "$1" ;;
*.pdf) pdftotext "$1" - || pdfpreview "$1" || file "$1" ;;
*.png | *.jpg | *.JPG | *.jpeg | *.gif | *.webp) imagepreview "$1" "$2" ;;
*.mp4 | *.mkv | *.mov | *.avi | *.m4v) videopreview "$1" "$2" ;;
*.mp3) audiopreview "$1" ;;
*.sketch) sketchpreview "$1";;
*.json) jq -C < "$1";;
*.csv) xsv table "$1";;
*) everythingelse "$1" ;;
esac
