#! /bin/sh

# cd
alias -- -='cd -'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'

# builtins
alias mkdir='mkdir -p'
alias clear="tput clear"
alias clera='clear'
alias clea='clear'
alias tclear='clear && tmux clear-history'
alias chmox='chmod +x'
alias ls='lsd'
alias l='ls'
alias la='ls -A'
alias ll='ls -Alh'
alias c='clear && echo "" && pwd && ls'

# renames
alias rr=lf
alias rm=trash
alias lg=lazygit
alias lj=lazyjj
alias mk=,mk
alias to=,ca
alias dict=,dict
alias lk=,let-me-know
alias um=,urlmap
alias apr=,auto-pr
alias asi=,voice-assistant
alias mdh=,markdown-to-html

# random
alias wk="watch kubectl"
alias ax="axel -a -n 10"
alias ppid="ps -o ppid= -p"
alias brew="HOMEBREW_NO_AUTO_UPDATE=1 brew"
alias lynx='lynx -lss="~/.config/lynx/.lynx.lss" -cfg="~/.config/lynx/.lynx.cfg"'
alias sbnoah="noah -o ~sbdb/Resources"
alias acti="source .venv/bin/activate"
alias scratch="$EDITOR /tmp/scratch-$(date +%s)"
alias ,remote-work="ssh $EXPERIMENT_VM"
alias s=",save"
alias pwdp="pwd|p"
alias research="cd $HOME/dev/docs/research && opencode"
alias gh="GIT_DIR=\$GIT_ROOT_DIR gh" # since we don't colocate git dir anymore
alias bb=",bm" # bookmark-manager

# agents
alias aw=",agent-workspace"
alias aww=",agent-workspace update && jj"
alias ,gh-copilot="npx -y @github/copilot --allow-tool 'write'"

# fin
alias finc="fin -c"
alias fincc="fin -match"
alias fins="fin -session \$(fin -sessions | fzf | cut -d' ' -f1) -export html >/tmp/fin-session-export.html && open /tmp/fin-session-export.html"
alias finh="fin -export message | ,markdown-to-html"
alias finm="fin -export message | glow"

# esa
alias ec="esa -c"
alias ea="esa +auto"
alias bud="esa +qa"
alias co="esa +coder"
alias mem="esa +mem"
alias em=",emoji-picker"
alias brain="esa +brain"
alias mi="esa +michel"
alias rem=",reminder"
alias summ="esa summarize key points from"
alias post="esa Short twitter post with bullet points based on"
alias resp="esa +coder \$(cat ~/.config/datafiles/prompts/user/message-response.md)"
alias tk=",tweak"
alias eo="esa --show-output 1"
alias ep=',esa-with-prompt'
alias sonv="ec -m sonnet validate your previous statements" # sonnet supremacy

# editors
alias vim='nvim'
alias ivm='nvim'
alias e='emacsclient  -a "" --no-wait'
alias et='emacsclient -nw'

# git
alias gs='git status'
alias gma='git commit --amend'
alias gl='git lg'
alias gd='git diff'
alias gds='git diff --staged'
alias gdp="git diff @{1}.."
alias glp="git lg @{1}.."
alias gcob='git checkout -b'
alias gffu='git pull upstream --ff-only $(git rev-parse --abbrev-ref HEAD)'
alias gffo='git pull origin --ff-only $(git rev-parse --abbrev-ref HEAD)'

# jj
alias js="jj show"
alias jjj='jj new'
alias jd='jj diff'
alias jab='jj absorb'
alias jpu='jj git push'
alias jpua='jj git push --all'
alias jsk='jj squash'
alias jf='jj git fetch'
alias jfm='jj git fetch && jj new main'
alias jr='jj rebase -d'
alias jfr=',jfr'
alias jb='jj bookmark set'
alias je='jj edit'
alias jj-squash-multi="jj stack | fzf -m | cut -d' ' -f3 | JJ_EDITOR=true xargs -n1 jj squash -r"
alias jwu='jj workspace update-stale'
alias jnm='jj git fetch && jj new main 2>/dev/null || jj new master'
alias ,gcl="jj git clone --colocate"

# taskwarrior
alias tsk='task rc.verbose=label -BLOCKED list'

# linux only
if [ "$OSTYPE" = "linux" ]; then
    alias caffeinate='systemd-inhibit tail -f /dev/null'
    alias suspend='systemctl suspend'
    alias dr="dragon -x"
    alias lim="cpulimit -l 200 -i --"
fi

# global
alias -g JL="cut -d{ -f2-|sed 's|^|{|'" # pull json part out of a log line (assume first { is start)
