#! /bin/sh

# cd
alias -- -='cd -'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'

# simple
alias mkdir='mkdir -p'
alias clera='clear'
alias clea='clear'
alias chmox='chmod +x'

# ls
alias ls='lsd'
alias l='ls'
alias la='ls -A'
alias ll='ls -Alh'

# random
alias rr=lf
alias rm=trash
alias k="kubecolor --light-background"
alias kk=kubectl
alias wk="watch kubectl"
alias brew='HOMEBREW_NO_AUTO_UPDATE=1 brew'
alias ax="axel -a -n 10"
alias lynx='lynx -lss="~/.config/lynx/.lynx.lss" -cfg="~/.config/lynx/.lynx.cfg"'
alias c='clear && echo "" && pwd && ls'
alias wf='venv activate'
alias yd='youtube-dl'
alias ydp='youtube-dl -o "%(playlist_index)s_%(title)s.%(ext)s"'
alias sbnoah='noah -o ~sbdb/Resources'
alias lg='lazygit'
alias lj='lazyjj'
alias mk=',mk'
alias asi=',voice-assistant'
alias lll='aichat --model ollama:granite3-dense:2b'
alias tk='fn(){,tweak "$*" && pbpaste | mdclip};fn'
alias aw=",agent-workspace"
alias aww=",agent-workspace update && jj"

# esa
alias e="esa"
alias ec="esa -c"
alias ea="esa +auto"
alias bud="esa +qa"
alias co="esa +coder"
alias mem="esa +mem"
alias em=",emoji-picker"
alias brain="esa +brain"
alias eout="esa --show-output 1 | glow -p"

# ledger
alias ledger='ledger -f ~/.local/share/ledger/master.ledger --strict'
alias ,ledger-bal='ledger bal'
alias ,ledger-cashflow='ledger bal ^Income ^Expenses'
alias ,ledger-networth='ledger bal ^Assets ^Liabilities'

# tmux
alias ta='tmux attach -t'
alias tn='tmux new-session -s'
alias tl='tmux list-sessions'

# editors
alias vim='nvim'
alias ivm='nvim'
alias et='emacsclient -nw'

# remote
alias ,remote-work="ssh $EXPERIMENT_VM"

# git
alias gs='git status'
alias gma='git commit --amend'
alias gl='git lg'
alias gd='git diff'
alias gds='git diff --staged'
alias gdp="git diff @{1}.."
alias glp="git lg @{1}.."
alias gcob='git checkout -b'
alias gffu='git pull upstream --ff-only $(git rev-parse --abbrev-ref HEAD)'
alias gffo='git pull origin --ff-only $(git rev-parse --abbrev-ref HEAD)'
alias ,gcl="git clone --recurse-submodules"

# jj
alias js="jj st"
alias jjj='jj new'
alias jd='jj diff'
alias jpu='jj git push --allow-new'
alias jsk='jj squash'
alias jf='jj git fetch'
alias jr='jj rebase -d'
alias jb='jj bookmark set'
alias jbm=',jj-bookmark-move'
alias je='jj edit'
alias jab='jj abandon'
alias jj-squash-multi="jj log | fzf -m | cut -d' ' -f3 | xargs -n1 jj squash -r"
alias jwu='jj workspace update-stale'

# utils
alias ppid='ps -o ppid= -p'

# other
if [ "$OSTYPE" = "linux" ]; then
    alias caffienate='systemd-inhibit tail -f /dev/null'
    alias suspend='systemctl suspend'
    alias dr="dragon -x"
    alias lim="cpulimit -l 200 -i --"
fi

# shorthand
alias to=,ca
alias dict=,dict
alias lk=,let-me-know
alias um=,urlmap

# just be nice dammit
alias go="nice go"
alias dlv="nice dlv"
alias golangci-lint="nice golangci-lint"

# global
alias -g JL="cut -d{ -f2-|sed 's|^|{|'"

# logseq
alias jrnl=" ,logseq-cli journal"
alias todo=" ,logseq-cli todo"

# aider
alias aider-flash="aider --model gemini/gemini-2.0-flash-exp"
alias aider-deepseek="aider --model openrouter/deepseek/deepseek-chat --edit-format=diff --no-show-model-warnings"
alias aider-fix="aider --test --test-cmd"
alias aider-sonnet="OPENAI_API_BASE=https://api.githubcopilot.com OPENAI_API_KEY=\$COPILOT_API_KEY aider --model openai/claude-3.7-sonnet --no-show-model-warnings --edit-format=diff"
alias aider-copilot="OPENAI_API_BASE=https://api.githubcopilot.com OPENAI_API_KEY=\$COPILOT_API_KEY aider --model openai/gpt-4.1 --no-show-model-warnings --edit-format=diff"
