[user]
name = "Abin Simon"
email = "mail@meain.io"

[ui]
default-command = "l"
pager = ["sh", "-c", "diff-so-fancy | less -RFX"]
conflict-marker-style = "git"
# editor = "emacsclient"
diff-editor = ":builtin"
# log-synthetic-elided-nodes = true # NOTE: what is this?
# graph.style = "square"

[ui.diff]
format = "git"
# tool = ["difft", "--color=always", "$left", "$right"]

[colors]
"diff removed token" = { underline = false }
"diff added token" = { underline = false }

[revset-aliases]
"stack(r)" = "r | ancestors(descendants(immutable_heads()..r), 2)"
"mine" = "remote_bookmarks() & (mine() | committer('mail@meain.io') | bookmarks('main') | bookmarks('master'))"
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'user(x)' = 'author(x) | committer(x)'

[aliases]
stack = ["log", "-r", "stack(@)"]
mine = ["log", "-r", "mine"]
l = ["log", "--limit", "10"]
# l = ["log", "-r", "ancestors(reachable(@, mutable()), 2)"]
tug = ["bookmark", "move", "--from", "closest_bookmark(@)", "--to", "@"] # update the bookmark
rebase-all = ["rebase", "-s", "all:roots(trunk()..mutable())", "-d", "trunk()"] # another option at https://github.com/jj-vcs/jj/discussions/4974
blame = ["file", "annotate"]
nm = ["new", "trunk()"]
e = ["edit"]

[templates]
log = 'personal_log_oneline'

draft_commit_description = '''
concat(
  description,
  "\n",
  indent(
    "JJ: ",
    concat(
      "Author: " ++ format_detailed_signature(author) ++ "\n",
      "Committer: " ++ format_detailed_signature(committer)  ++ "\n",
      "\n",
      diff.stat(76),
      "\n",
      diff.git(),
    ),
  ),
)
'''

[template-aliases]
# https://martinvonz.github.io/jj/latest/config/#display-of-commit-and-change-ids
'format_short_id(id)' = 'id.shortest(5)'
'format_timestamp(timestamp)' = 'timestamp.ago()'

# Refer to jj/cli/src/config/templates.toml
personal_log_oneline = '''
if(root,
  format_root_commit(self),
  label(if(current_working_copy, "working_copy"),
    concat(
      separate(" ",
        format_short_change_id_with_hidden_and_divergent_info(self),
        if(bookmarks, "[" ++ bookmarks ++ "]"),
        tags,
        working_copies,
        if(git_head, label("git_head", "HEAD")),
        if(conflict, label("conflict", "conflict")),
        if(empty, label("empty", "(empty)")),
        if(description,
          description.first_line(),
          label(if(empty, "empty"), description_placeholder),
        ),
      ) ++ "\n",
    ),
  )
)
'''

[lazyjj]
highlight-color = "#f1f1f1"

[git]
push-bookmark-prefix = "meain/"
