[model_aliases]
  # openai
  ogpt = "openai/gpt-5.4"
  omini = "openai/gpt-5.4-mini"
  onano = "openai/gpt-5.4-nano"

  # github
  ghgpt = "github/gpt-5.4"
  ghmini = "github/gpt-5.4-mini"
  ghnano = "github/gpt-5.4-nano"

  # groq
  groq = "groq/openai/gpt-oss-120b"

  # ollama
  qwen = "ollama/qwen3:4b"
  jan = "ollama/hf.co/Menlo/Jan-nano-gguf:Q4_K_M"

  # openrouter
  mercury = "openrouter/inception/mercury-coder-small-beta"

  # copilot
  gpt = "copilot/gpt-5.4"
  mini = "copilot/gpt-5-mini"
  codex = "copilot/gpt-5.3-codex"
  cgemini = "copilot/gemini-2.5-pro"
  csonnet = "copilot/claude-sonnet-4.6"
  copus = "copilot/claude-opus-4.6"
  chaiku = "copilot/claude-haiku-4.5"
  cgrok = "copilot/grok-code-fast-1"

  # anthropic
  haiku="anthropic/claude-haiku-4-5"
  sonnet="anthropic/claude-sonnet-4-5"
  opus="anthropic/claude-opus-4-6"

[settings]
  show_commands=true
  default_model="sonnet"

