#!/bin/sh

PATH="/usr/local/bin:/usr/bin"
if pgrep "mpv" > /dev/null 2>&1;then
    /usr/local/bin/mpvc next
elif pgrep "Spotify" > /dev/null 2>&1;then
    /usr/local/bin/spotify next
else
    /usr/local/bin/mpc next
fi
/usr/local/bin/tmux refresh-client -S
