#!/bin/sh

PATH="/usr/local/bin:/usr/bin"
if pgrep "mpv" > /dev/null 2>&1;then
    /usr/local/bin/mpvc toggle
elif pgrep "Spotify" > /dev/null 2>&1;then
    /usr/local/bin/spotify p
else
    /usr/local/bin/mpc toggle
fi
/usr/local/bin/tmux refresh-client -S
