#!/bin/sh

PATH="/usr/local/bin:/usr/bin:/bin"
if pgrep "mpv" > /dev/null 2>&1;then
    /usr/local/bin/mpvc prev
elif pgrep "Spotify" > /dev/null 2>&1;then
    /usr/local/bin/spotify back
else
    /usr/local/bin/mpc prev
fi
/usr/local/bin/tmux refresh-client -S
