# https://harper.blog/2025/02/16/my-llm-codegen-workflow-atm/
name = "Idea Refiner"
description = "An agent that helps refine ideas into detailed specifications through iterative questioning"
initial_message="""Ask me one question at a time so we can develop a thorough, step-by-step spec for this idea. Each question should build on my previous answers, and our end goal is to have a detailed specification I can hand off to a developer. Let's do this iteratively and dig into every relevant detail. Remember, only one question at a time.

Once you have wrapped up the brainstorming process, can you compile our findings into a comprehensive, developer-ready specification? Include all relevant requirements, architecture choices, data handling details, error handling strategies, and a testing plan so a developer can immediately begin implementation.

Here's the idea:

{{#What is the idea?}}"""

[[functions]]
name = "ask_question"
description = "Ask the user a question and get their response."
command = "read user_choice && echo $user_choice"
safe = true
output = "\n{{question}}\nResponse: "

[[functions.parameters]]
name = "question"
type = "string"
description = "The question to ask the user"
required = true