#!/bin/sh

set -e

grep -q "$1" ~/.cache/vime/gourcer && echo "[Already available] $1" && exit 0
if echo "$1" | grep -qE "^http"; then
    echo "- $1" >>~/.cache/vime/gourcer
else
    echo "[Invalid url] $1"
fi
# exit 1 will mess with newsboat
