#!/bin/bash

set -e

url="$(curl -s https://www.bing.com|pup '.img_cont'|
    grep -o 'url([^)]*'|
    sed 's|url(|https://www.bing.com|;s|_1920x1080|_1920x1200|g;s|&amp;.*||')"
dir='/tmp/bing-images/'
pic="$dir$(date +%y%m%d).jpg"

mkdir -p $dir
[ "$url" == "$(cat /tmp/bing-images/picurl)" ] || curl -so "$pic" "$url"
echo "$url" > /tmp/bing-images/picurl
echo "$pic"
