#!/bin/sh
set -e

randPic="$(find "$HOME/Pictures" | grep -E '.(png|jpg|jpeg)$' | shuf -n1)"
mv "$randPic" /tmp/wallpaper

osascript -e 'tell application "Finder" to set desktop picture to POSIX file "/tmp/wallpaper"'
killall Dock
