#!/bin/sh

set -e

if [ -n "$1" ];then
    randPic="$1"
else
    randPic="$(find "/Users/meain/Pictures" | grep -E '.(png|jpg|jpeg)$' | shuf -n1)"
fi

newname="$HOME/Pictures/temp_$(date +%s)"
echo "$randPic"
cp "$randPic" "$newname"
osascript -e "tell application \"Finder\" to set desktop picture to POSIX file \"$newname\""
rm "$newname"
