#!/bin/sh

set -e

randPic="$(find "/Users/meain/Pictures" | grep -E '.(png|jpg|jpeg)$' | shuf -n1)"
osascript -e "tell application \"Finder\" to set desktop picture to POSIX file \"$randPic\""
killall Dock
