#!/bin/sh

set -e

dir="$HOME/.cache/chills"
mkdir -p "$dir" && cd "$dir"

download() {
    name="$(echo "$1" | awk '{print $1}')"
    url="$(echo "$1" | awk '{print $2}')"
    if [ ! -f "$name" ]; then
        youtube-dl -f 'bestaudio[ext=m4a]' --output "$name" "$url"
    fi
}

if [ "$1" = "cache" ]; then
    while read -r line; do
        download "$line"
    done <"$HOME/.config/datafiles/chills"
    exit 0
fi

item="$(fzf <"$HOME/.config/datafiles/chills")"
download "$item"
name="$(echo "$item" | awk '{print $1}')"
open "$name" # using open instead of mpv to start gui and detach
