#!/bin/sh

if [ -z "$1" ];then
    HOST=$(grep -E "^Host" "$HOME/.ssh/config" | sed 's/^Host //' | fzf)
else
    HOST="$1"
fi

if [ -z "$HOST" ];then
    exit 1
fi

if [ -n "$TMUX" ]; then
    tmux selectp -P bg=colour236
fi
ssh "$HOST"
tmux selectp -P default
