#!/bin/sh

set -e

fetch_and_show(){
    mkdir -p /tmp/newsboatpreviews
    mkdir -p /tmp/comics
    output="$(curl -L "$1")"
    name="/tmp/comics/$(echo "$output" | pup "$2" | head -n1)"
    echo "$output" | pup "$3" | xargs -I{} curl -L "$4" > "$name"
    open -g -a /Applications/Preview.app "$name"
}

case "$1" in
*theoatmeal.com*) fetch_and_show "$1" "title text{}" "#comic img attr{src}" "{}" ;;
*xkcd.com*) fetch_and_show "$1" "title text{}" "#comic img attr{src}" "https:{}" ;;
*commitstrip.com*) fetch_and_show "$1" "title text{}" ".entry-content img attr{src}" "{}" ;;
*explosm.net*) fetch_and_show "$1" "title text{}" "#comic-wrap img attr{src}" "https:{}" ;;
*feed.dilbert.com*) fetch_and_show "$1" "title text{}" ".img-comic attr{src}" "https:{}" ;;
*PoorlyDrawnLines*) fetch_and_show "$1" "title text{}" ".content.comic .post img attr{src}" "{}";;
*taleas.com*) fetch_and_show "$1" "title text{}" "#main_img attr{src}" "{}";;
esac
