#!/bin/sh

set -e

tmux capture-pane -pS -1000 > /tmp/ee-dump
L="$(grep ' ' /tmp/ee-dump | grep -vE '^.. {10}'| tac | tail -n+2 | fzf)"
# I would like to add a uniq in here, but cannot do that without sort, but if sorted we lose the order

COPY=0
OUTPUT=""
while read -r line; do
    if [ "$COPY" = 1 ];then
        if echo "$line" | grep -q " ";then
            COPY=0
        fi
        OUTPUT="$OUTPUT$line\n"
    fi
    if echo "$line" | grep -q "$L";then
        OUTPUT=""
        COPY=1
    fi
done < /tmp/ee-dump

{
    echo "$L"
    echo "$OUTPUT"
} | pbcopy
