#!/bin/sh

# diff last two yanks using maccy(brew cask install maccy) as the source

set -e

rdir="/tmp/ldiffs$(xxd -l2 -ps /dev/urandom)"
mkdir -p "$rdir"

DB=~/Library/Containers/org.p0deje.Maccy/Data/Library/Application\ Support/Maccy/Storage.sqlite
SQL="select   distinct ZVALUE
     from     ZHISTORYITEMCONTENT
     where    ZTYPE like '%text%'
     order by Z_PK desc"

sqlite3 "$DB" "$SQL limit 1" > "$rdir/left"
sqlite3 "$DB" "$SQL limit 1 offset 1" > "$rdir/right"
"${DIFFTOOL:-diff}" "$rdir/left" "$rdir/right"
