#!/bin/sh

set -e

url="$1"
filepath=$2

echo "downloading '$url' >>> '$filepath'" >>/tmp/downloaderqueue

cleanup() {
    # if file exists but download fails, error not reported
    [ -f "$filepath" ] || echo "failed '$url' >>> '$filepath'" >>/tmp/downloaderqueue
}
trap cleanup EXIT

temp="$(mktemp)"
curl -L "$1" >"$temp"
mkdir -p "$(dirname "$filepath")"
mv "$temp" "$filepath"
echo "complete '$url' >>> '$filepath'" >>/tmp/downloaderqueue
notify "Download complete" "$filepath\n\n$url"
