#! /bin/sh

clear
echo 'Checking stats.'
sleep 1

clear
echo 'Checking stats..'
sleep 1

clear
echo 'Checking stats...'
sleep 1

clear
echo '\n\n\n\n\n\n\n\n\n\n                                    Firing rocket in 3...'
sleep 1

clear
echo '\n\n\n\n\n\n\n\n\n\n                                    Firing rocket in 2...'
sleep 1

clear
echo '\n\n\n\n\n\n\n\n\n\n                                    Firing rocket in 1...'
sleep 1

clear
echo '\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n🚀'
sleep .05

clear
echo '\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n  🚀'
sleep .05

clear
echo '\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n    🚀'
sleep .05

clear
echo '\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n      🚀'
sleep .05

clear
echo '\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n        🚀'
sleep .05

clear
echo '\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n          🚀'
sleep .05

clear
echo '\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n            🚀'
sleep .05

clear
echo '\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n              🚀'
sleep .05

clear
echo '\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                🚀'
sleep .05

clear
echo '\n\n\n\n\n\n\n\n\n\n\n\n\n\n                  🚀'
sleep .05

clear
echo '\n\n\n\n\n\n\n\n\n\n\n\n                    🚀'
sleep .05

clear
echo '\n\n\n\n\n\n\n\n\n\n                      🚀'
sleep .05

clear
echo '\n\n\n\n\n\n\n\n                        🚀'
sleep .05

clear
echo '\n\n\n\n\n\n                          🚀'
sleep .05


clear
echo '\n\n\n\n\n\n                           🚀'
sleep .05

clear
echo '\n\n\n\n\n\n                            🚀'
sleep .05

clear
echo '\n\n\n\n\n                              🚀'
sleep .05

clear
echo '\n\n\n\n                                🚀'
sleep .05

clear
echo '\n\n\n                                  🚀'
sleep .05

clear
echo '\n\n                                    🚀'
sleep .05

clear
echo '\n                                      🚀'
sleep .05

clear
echo '\n                                                    🚀'
sleep .05

clear
echo '\n                                                      🚀'
sleep .05

clear
echo '\n                                                        🚀'
sleep .05

clear
echo '\n                                                          🚀'
sleep .05

clear
echo '\n\n\n\n\n\n\n\n\n\n                                  💥 Rocket fired! \n\n\n\n\n'
sleep .05
