#!/bin/sh

[ -n "$1" ] && echo "$(basename "$0") does not take any args" && exit 1

find . -name '*.mp3' |
    while read -r file; do
        title="$(ffprobe "$file" 2>&1 | grep 'title' | grep -o '[^:]*$' | sed 's| ||')"
        artist_or_album="$(ffprobe "$file" 2>&1 | grep -E '^\ *(album|artist)' | head -n1 | grep -o '[^:]*$' | sed 's| ||')"
        [ -z "$title" ] && [ -z "$artist_or_album" ] && continue
        [ "$file" = "./$title - $artist_or_album.mp3" ] && continue
        mv -v "$file" "$title - $artist_or_album.mp3"
    done
