#!/bin/sh

set -e

urls="$(cat "/dev/stdin" |
    grep -oE '(https?|ftp|file):/?//[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%~_|]' |
    tee /tmp/githubmailopen |
    sort -u)"

if [ "$(echo "$urls" | grep "#issuecomment-[0-9][0-9]*" | wc -l | sed 's|^ *||')" = "1" ]; then
    echo "$urls" | grep "#issuecomment-[0-9][0-9]*" | xargs open
elif [ "$(echo "$urls" | grep "/pull/[0-9][0-9]*/files/" | wc -l | sed 's|^ *||')" = "1" ]; then
    echo "$urls" | grep "/pull/[0-9][0-9]*/files/" | xargs open
elif [ "$(echo "$urls" | grep "/pull/[0-9][0-9]*" | wc -l | sed 's|^ *||')" = "1" ]; then
    echo "$urls" | grep "/pull/[0-9][0-9]*" | xargs open
elif [ "$(echo "$urls" | grep "#discussion_r[0-9][0-9]*" | wc -l | sed 's|^ *||')" = "1" ]; then
    echo "$urls" | grep "#discussion_r[0-9][0-9]*" | xargs open
elif [ "$(echo "$urls" | grep "#event-[0-9][0-9]*" | wc -l | sed 's|^ *||')" = "1" ]; then
    echo "$urls" | grep "#event-[0-9][0-9]*" | xargs open
elif [ "$(echo "$urls" | grep "#commitcomment-[0-9][0-9]*" | wc -l | sed 's|^ *||')" = "1" ]; then
    echo "$urls" | grep "#commitcomment-[0-9][0-9]*" | xargs open
elif [ "$(echo "$urls" | grep "/actions/runs/[0-9][0-9]*" | wc -l | sed 's|^ *||')" = "1" ]; then
    echo "$urls" | grep "/actions/runs/[0-9][0-9]*" | xargs open
else
    echo "$urls" | FZF_DEFAULT_OPTS='
    -1 -0
    --prompt=" "
    --inline-info
    --color fg:248,hl:250,fg+:232,bg+:231,hl+:2
    --color info:108,prompt:242,spinner:108,pointer:1,marker:168
' fzf | xargs open -g
fi
