#!/bin/sh

set -e

urls="$(grep -oE '(https?|ftp|file):/?//[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%~_|]' | sort -u)"

MARKERS="#issuecomment-[0-9][0-9]*
/pull/[0-9][0-9]*/files/
/pull/[0-9][0-9]*$
#discussion_r[0-9][0-9]*
#event-[0-9][0-9]*
#commitcomment-[0-9][0-9]*
/actions/runs/[0-9][0-9]*"

for marker in $MARKERS; do
    if [ "$(echo "$urls" | grep -c "$marker")" = "1" ]; then
        echo "$urls" | grep "$marker" | xargs open && exit 0
    fi
done
echo "$urls" | FZF_DEFAULT_OPTS='
-1 -0
--prompt=" "
--inline-info
--color fg:248,hl:250,fg+:232,bg+:231,hl+:2
--color info:108,prompt:242,spinner:108,pointer:1,marker:168
' fzf | xargs open -g
