#!/bin/sh

set -e

# check if we have items to push
grep -qE '^-' ~/.cache/vime/gourcer || exit 0

cd ~/Documents/Projects/projects/gourcer
git pull origin master --rebase
cat ~/.cache/vime/gourcer >>pending
git add pending
[ -f repo ] && rm repo && git add repo
rm ~/.cache/vime/gourcer && touch ~/.cache/vime/gourcer
git commit -m 'Update pending items'
git push origin master
