#!/bin/sh

set -e

# task '/add gourcer entries/' && gource-publish
if ! task '/add gourcer entries/'; then
    echo "Looks like we already did it. Bye" && exit 0
fi
items="$(grep -E '^-' ~/.cache/vime/gourcer | head -n4 | awk '{print $2}')"
echo "$items" | xargs -L1 echo gourcer

changes="$(echo "$items" | awk '{print "s|- "$1"|x "$1"|;"}' | tr -d '\n')"
sed -ibk "$changes" ~/.cache/vime/gourcer
rm ~/.cache/vime/gourcerbk

task '/add gourcer entries/ status:pending' 'done'
