#!/bin/sh

set -e

if [ -f "Cargo.toml" ]; then
    version="$(tojson Cargo.toml | jq -r '.package.version')"
elif [ -f "setup.py" ];then
    version="$(grep version= setup.py | cut -d'"' -f2)"
fi

[ -z "$version" ] && exit 1

git tag -l | grep -q "$version" && echo "Update version first." && exit 1
echo "Using tag $version"
git tag "$version"
git push --tags
