#!/bin/sh

set -e

if [ -z "$1" ];then
    CHECKOUT_LOC="$(git log --oneline | fzf | cut -d' ' -f1)"
else
    CHECKOUT_LOC="$1"
fi


DIR="$(date '+%s')"
FULLDIR="/tmp/howwasit/$DIR"
mkdir -p "$FULLDIR"
cp -r .git "$FULLDIR"
cd "$FULLDIR"
git reset --hard HEAD
git checkout "$CHECKOUT_LOC"
"$EDITOR" .
rm -rf "$FULLDIR"
