#!/bin/sh

set -e

DIR="$HOME/.local/share/journal"
mkdir -p "$DIR"

view=0
search=0

[ "$1" = 'view' ] && view=1 && shift
[ "$1" = 'search' ] && search=1 && shift
if [ -z "$1" ]; then
    cd "$DIR"
    FILE="$DIR/$(date '+%Y/%m/%d').md"
    mkdir -p "$(dirname "$FILE")"
else
    FILE="$(echo "$1" | sed 's|.asc$||')"
fi

# view and exit if view
if [ "$view" = 1 ]; then
    gpg --decrypt "$FILE.asc" 2>/dev/null
    exit 0
fi

# Search through items
if [ "$search" = 1 ]; then
    find "$DIR" -name '*.md.asc' | sed "s|^$DIR/||;s|.md.asc$||" | sort |
        fzf --preview "gpg --decrypt $DIR/{}.md.asc 2>/dev/null" --preview-window 90% --height 100%
    exit 0
fi

# encrypt if available
if [ -f "$FILE.asc" ]; then
    gpg --decrypt "$FILE.asc" >"$FILE" 2>/dev/null
    cat "$FILE" >"$FILE.bkp"
fi

# create new if no entry for today available
if [ -f "$FILE" ]; then
    echo "" >>"$FILE"
else
    touch "$FILE" "$FILE.bkp"
fi

# open with current time prefilled
echo "== $(date '+%T') ==" >>"$FILE"
"$EDITOR" "$FILE"

# save only if file changed
if ! diff -q "$FILE" "$FILE.bkp" >/dev/null 2>&1; then
    [ -f "$FILE.asc" ] && rm "$FILE.asc"
    gpg --encrypt --sign --armor -r abinsimon10@gmail.com "$FILE" 2>/dev/null
    git add ./*.asc &&
        git commit -m '[autocommit] update journal' >/dev/null 2>&1
    echo "Journal updated."
    task '/add journal entry/ status:pending' 'done'
else
    echo "No updates."
fi

rm "$FILE" "$FILE.bkp"
