#!/bin/sh

set -e

MAILS=$(~/.bin/notifyableunreadmails | cut -c-50)
COUNT=$(echo "$MAILS" | wc -l)
osascript -e "display notification \"$MAILS\" with title \"$COUNT unread mails\""
tmux refresh-client 2> /dev/null || exit 0
