#!/bin/bash
# https://notmuchmail.org/pipermail/notmuch/2019/028956.html

set -e

MAILDIR=$HOME/.local/share/mail/meain
NOTMUCH_CONFIG="$HOME/.config/notmuch/config"

# Move a message file while removing its UID-part
function safeMove { s=${1##*/}; s=${s%%,*}; mv -f $1 $2/$s; }

# Move all archived messages from Inbox to Archive folder
echo Moving $(notmuch count --output=files 'folder:meain/INBOX' and -tag:inbox) \
     archived messages from Inbox to Archive folder
for i in $(notmuch search --output=files 'folder:meain/INBOX' and -tag:inbox); do
    safeMove $i ${MAILDIR}/Archive/cur
done
