#!/bin/sh

set -e

unreadsenders
(isheadphonesconnected > /dev/null || isaudiojackconnected > /dev/null) && \
    unreadsenders | sed 's/^-/*/' | sed 's/(\([^(]*\))$/from \1/' | say -v Alex --rate 400
