#!/bin/sh

set -e

export NOTMUCH_CONFIG="$HOME/.config/notmuch/config"
if [ ! "$1" = "retag" ];then
    /usr/local/bin/mbsync -a || echo "Could not pull new emails"
fi

notmuch new 2>/dev/null

# reindex inbox
notmuch tag -inbox tag:inbox
notmuch tag +inbox 'folder:/INBOX/'

#github
notmuch tag +github 'folder:/INBOX/' 'from:notifications@github.com'

# newsletters
notmuch tag +newsletter +nonotify 'folder:/INBOX/' 'from:yo@dev.to'
notmuch tag +newsletter +nonotify 'folder:/INBOX/' 'from:noreply@medium.com'
notmuch tag +newsletter +nonotify 'folder:/INBOX/' 'from:no-reply@dribbble.com'
notmuch tag +newsletter +nonotify 'folder:/INBOX/' 'from:no-reply@screener.in'
notmuch tag +newsletter +nonotify 'folder:/INBOX/' 'from:do-not-reply@stackoverflow.email'
notmuch tag +newsletter +nonotify 'folder:/INBOX/' 'from:jess@dev.to'
notmuch tag +newsletter +nonotify 'folder:/INBOX/' 'from:npm@npmjs.com'

# bullshit
notmuch tag +bullshit +nonotify 'folder:/INBOX/' 'from:marketradar@newsletter.geojit.net'
notmuch tag +bullshit +nonotify 'folder:/INBOX/' 'from:no-reply@updates.bookmyshow.com'
notmuch tag +bullshit +nonotify 'folder:/INBOX/' 'from:assistant-noreply@google.com'
notmuch tag +bullshit +nonotify 'folder:/INBOX/' 'from:informations@hdfcbank.net'
notmuch tag +bullshit +nonotify 'folder:/INBOX/' 'from:no-reply@spotify.com'
notmuch tag +bullshit +nonotify 'folder:/INBOX/' 'from:fnalerts-no-reply@firstnaukri.com'
notmuch tag +bullshit +nonotify 'folder:/INBOX/' 'from:irctctourismoffers@irctc.co.in'
notmuch tag +bullshit +nonotify 'folder:/INBOX/' 'from:noreply@newsletter.geojit.net'
notmuch tag +bullshit +nonotify 'folder:/INBOX/' 'from:communications@nsdl.com'
notmuch tag +bullshit +nonotify 'folder:/INBOX/' 'from:no-reply@entertainment.bookmyshow.com'

# known
notmuch tag +known +nonotify 'folder:/INBOX/' 'from:noreply@swiggy.in'
notmuch tag +known +nonotify 'folder:/INBOX/' 'from:uber.india@uber.com'
notmuch tag +known +nonotify 'folder:/INBOX/' 'from:no-reply@swiggy.in'
notmuch tag +known +nonotify 'folder:/INBOX/' 'from:rapidocare@acko.com'
notmuch tag +known +nonotify 'folder:/INBOX/' 'from:info@meetup.com'
notmuch tag +known +nonotify 'folder:/INBOX/' 'from:no-reply@paytm.com'
notmuch tag +known +nonotify 'folder:/INBOX/' 'from:noreply@olacabs.com'
notmuch tag +known +nonotify 'folder:/INBOX/' 'from:support@vendekin.com'
notmuch tag +known +nonotify 'folder:/INBOX/' 'from:info@gokhana.com'

# not so important
notmuch tag +nonimportant +nonotify 'folder:/INBOX/' 'from:info@bseindia.in'
notmuch tag +nonimportant +nonotify 'folder:/INBOX/' 'from:hello@splitwise.com'
notmuch tag +nonimportant +nonotify 'folder:/INBOX/' 'from:notifications-noreply@linkedin.com'
notmuch tag +nonimportant +nonotify 'folder:/INBOX/' 'from:linkedin@e.linkedin.com'
notmuch tag +nonimportant +nonotify 'folder:/INBOX/' 'from:alerts@ifttt.com'
notmuch tag +nonimportant +nonotify 'folder:/INBOX/' 'from:windowsinsiderprogram@e-mail.microsoft.com'
notmuch tag +nonimportant +nonotify 'folder:/INBOX/' 'from:no-reply@sampark.gov.in'
notmuch tag +nonimportant +nonotify 'folder:/INBOX/' 'from:upvote-noreply@quora.com'
notmuch tag +nonimportant +nonotify 'folder:/INBOX/' 'from:pro@codecademy.com'
notmuch tag +nonimportant +nonotify 'folder:/INBOX/' 'from:no-reply@mailer.bookmyshow.com'

# others
notmuch tag +python +nonotify 'folder:/INBOX/' 'subject:/\[Python-Dev\]/'
notmuch tag +git +nonotify 'folder:/INBOX/' 'to:git@vger.kernel.org'
notmuch tag +bank 'folder:/INBOX/' 'from:alerts@hdfcbank.net'
