#!/bin/bash
# https://notmuchmail.org/pipermail/notmuch/2019/028956.html

set -e

MAILDIR=$HOME/.local/share/mail/meain
# NOTMUCH_CONFIG="$HOME/.config/notmuch/config"

# Move a message file while removing its UID-part
function safeMove { mv -f "$1" "$2/$(echo "$1"|xargs basename|cut -d',' -f1)"; }

# Move all archived messages from Inbox to Archive folder
echo Moving $(notmuch count --output=files 'folder:meain/INBOX' and -tag:inbox) \
     archived messages from Inbox to Archive folder
for i in $(notmuch search --output=files 'folder:meain/INBOX' and -tag:inbox|grep 'meain/INBOX'); do
    safeMove "$i" "$MAILDIR/[Gmail].All Mail/cur"
done
