#!/bin/sh

count=$(ls "$HOME"/.local/share/mail/meain/INBOX/new | wc -l | sed 's/^\ *//')
if [ "0" -ne "$count" ];then
    osascript -e "display notification \"$count unread emails\" with title \"New email\""
    osascript -e "say \"dum\""
fi
