#!/bin/sh

set -e

NEWMAILS=$(unreadsenders)
if [ -n "$NEWMAILS" ]; then
    echo "$NEWMAILS"
    echo "$(echo "$NEWMAILS" | wc -l) unread mail" | say -v Alex --rate 300
    sleep 0.5 
    (isheadphonesconnected >/dev/null || isaudiojackconnected >/dev/null) &&
        unreadsenders | sed 's/^/* /' | say -v Alex --rate 300
fi
