#!/usr/local/bin/python3
import os
import sys
import time
import random

colors = ["\033[95m", "\033[94m", "\033[92m", "\033[93m", "\033[91m", "\033[0m"]

height, width = [int(c) for c in os.popen("stty size", "r").read().split()]
meain = """
 ███▄ ▄███▓▓█████ ▄▄▄       ██▓ ███▄    █ 
▓██▒▀█▀ ██▒▓█   ▀▒████▄    ▓██▒ ██ ▀█   █ 
▓██    ▓██░▒███  ▒██  ▀█▄  ▒██▒▓██  ▀█ ██▒
▒██    ▒██ ▒▓█  ▄░██▄▄▄▄██ ░██░▓██▒  ▐▌██▒
▒██▒   ░██▒░▒████▒▓█   ▓██▒░██░▒██░   ▓██░
░ ▒░   ░  ░░░ ▒░ ░▒▒   ▓▒█░░▓  ░ ▒░   ▒ ▒ 
░  ░      ░ ░ ░  ░ ▒   ▒▒ ░ ▒ ░░ ░░   ░ ▒░
░      ░      ░    ░   ▒    ▒ ░   ░   ░ ░ 
       ░      ░  ░     ░  ░ ░           ░ 
""".split(
    "\n"
)

mwidht = 42
mheight = 9

starth = int(height / 2 - mheight / 2)
startw = int(width / 2 - mwidht / 2)

turn = 0
while True:
    BLOCK = " "
    color = colors[random.randrange(0, 6)]
    if turn % 2 == 0:
        BLOCK = " "
    else:
        time.sleep(1)
    for i in range(height):
        if i >= starth and i - starth < mheight and turn % 2 == 0:
            initial_spacing = startw - 1
            remaingin_space = 0
            sys.stdout.write("%s" % color)
            print(BLOCK * initial_spacing, meain[i - starth], BLOCK * remaingin_space)
            sys.stdout.write("%s" % colors[-1])
        else:
            print(BLOCK * width)
    turn += 1
    time.sleep(.5)
