#!/bin/sh

set -e

ITEM="$(youtube-dl "$1" -F | grep -v 'video only' | awk '{print $1,$4}' | grep '720p' | head -n1 | awk '{print $1}')"
if [ -n "$ITEM" ]; then
    youtube-dl "$1" -f "$ITEM" --output "$HOME/Desktop/newsboat-downloads/youtube/%(uploader)s/%(title)s.%(ext)s" &&
        notify "Download complete" "$(youtube-dl --get-title "$1")"
else
    youtube-dl "$1" --output "$HOME/Desktop/newsboat-downloads/youtube/%(uploader)s/%(title)s.%(ext)s" &&
        notify "Download complete" "$(youtube-dl --get-title "$1")" ||
        open "$1"
fi
