#!/bin/sh

set -e

export TS_MAXFINISHED="13"
mkdir -p "$HOME/.cache/newsboat"
echo "$1" >>"$HOME/.cache/newsboat/preview"
osascript -e "display notification \"Adding $1 to queue\" with title \"Newsboat\""

comicdownload() {
    TS_SOCKET="/tmp/quick" ts comicdownload "$1"
}

youtubedownload() {
    ts youtubedownload "$1"
}

case "$1" in
*theoatmeal.com*) comicdownload "$1" ;;
*xkcd.com*) comicdownload "$1" ;;
*commitstrip.com*) comicdownload "$1" ;;
*explosm.net*) comicdownload "$1" ;;
*feed.dilbert.com*) comicdownload "$1" ;;
*PoorlyDrawnLines*) comicdownload "$1" ;;
*youtube.com*) youtubedownload "$1" ;;
*youtu.be*) youtubedownload "$1" ;;
*) open "$1" ;;
esac
