#!/bin/sh

set -e

mkdir -p '/tmp/markdownpdfrenders'
filename="/tmp/markdownpdfrenders/$(date '+%s').pdf"


pandoc -f gfm\
    --highlight-style=espresso\
    --pdf-engine=lualatex\
    -V mainfont:anonymouspro\
    -V monofont:firacodelight\
    -V documentclass:extarticle\
    -V fontsize:14pt -o "$filename" "$1"
qlmanage -p "$filename" >/dev/null 2>&1

