#!/bin/sh

set -e

fixpodpath |
    while read -r line; do
        url="$(echo "$line" | cut -d'"' -f1)"
        path="$(echo "$line" | cut -d'"' -f2)"
        [ ! -f "$path" ] && tmuxqueue "downloader '$url' '$path'"
    done
