#!/bin/sh

set -e

[ -z "$1" ] && exit
if echo "$1" | grep -qE '^xhttps?\:\/\/[a-z0-9_\.\?\&\=#-]+';then
   URL="$(echo "$1"|cut -c2-)"  # this is from the seperator in neomutt
   tmux popup -w90% -h90% -KE -d '#{pane_current_path}' -R "lynx -lss='~/.lynx.lss' '$URL'"
elif echo "$1" | grep -qE '^https?\:\/\/[a-z0-9_\.\?\&\=#-]+';then
   tmux popup -w90% -h90% -KE -d '#{pane_current_path}' -R "lynx -lss='~/.lynx.lss' '$1'"
else
   tmux popup -w90% -h90% -KE -d '#{pane_current_path}' -R "nvim '$1'"
fi
