#!/bin/sh

set -e

if [ "$(tmux display-message -p -F "#{session_name}")" = "popup" ];then
    tmux detach-client
else
    tmux popup -d '#{pane_current_path}' -x100% -y0% -w50% -h50% -K -E -R "tmux attach -t popup || tmux new -s popup" || true
fi
