#!/bin/sh

set -e

file=~/.cache/rain.ogg
url=https://rainymood.com

[ -f "$file" ] ||
youtube-dl -c --extract-audio --audio-quality 0 \
              --audio-format vorbis --prefer-ffmpeg \
              --no-playlist "$url" -o "$file"

exec mpv "$file"
