#!/bin/sh

if [ -z "$1" ];then
    if [ -f "README.md" ];then
        pandoc "README.md" | lynx -lss="~/.lynx.lss" -stdin
    else
        echo "Usage: readmd <filename>"
    fi
else
    pandoc "$1" | lynx -lss="~/.lynx.lss" -stdin
fi
