#!/bin/sh

set -e

TNAME="$(pwd|xargs basename)"
IGNORE_STRING=""
if [ -f .dockerignore ];then
    IGNORE_STRING="$(sed '/^\ *$/d;s|^|--exclude |' .dockerignore | tr '\n' ' ')"
fi

rsync -azvr --exclude '.git' $IGNORE_STRING . "$EXPERIMENT_VM:/tmp/$TNAME"

[ "$1" = "sync" ] && exit 0

if [ "$1" = "run" ];then
    TERM=screen-256color ssh "$EXPERIMENT_VM" -t "cd /tmp/$TNAME && bash -c '$*'"
else
    TERM=screen-256color ssh "$EXPERIMENT_VM" -t "cd /tmp/$TNAME && bash"
fi
