#!/bin/sh

set -e

RFILE="resources"

if [ "$1" = "new" ]; then
    cd ~/.notes/resources
    printf "Name: "
    read -r
    RFILE="$(echo "$REPLY" | tr ' ' '-')"
    touch "$RFILE"
    exit
else
    if [ ! -f "$RFILE" ]; then
        cd ~/.notes/resources
        RFILE=$(fzf)
    fi
fi

[ "$1" = l ] && cat "$RFILE" && exit 0
[ "$1" = o ] && fzf <"$RFILE" | xargs -I{} open "{}" && exit 0
echo "$1" | grep -qE "^http" && echo "$1" >>"$RFILE" && exit 0

grep -q "$(pbpaste)" "$RFILE" && echo "$(tput setaf 1)[Already available]$(tput sgr0) $(pbpaste)" && exit 1
echo "$RFILE < $(pbpaste)"
echo "$(pbpaste)" >>"$RFILE" # echo is kept is so that it inserts a newline
