#!/bin/sh

set -e

NOTES_FOLDER="$HOME/.notes/resources"

get_file() {
    [ -f "resources" ] && echo "resources" && return
    FILE="$(command ls -t1 "$NOTES_FOLDER" | fzf --preview "cat $NOTES_FOLDER/{}" --query "$1")"
    echo "$NOTES_FOLDER/$FILE"
}

list() {
    cat "$(get_file "$*")"
}
fzf_items() {
    fzf -m --preview-window up:1 --preview 'echo {} | sed "s|^.[^ ]* ||"' <"$(get_file "$*")"
}
get() {
    fzf_items "$*" | awk '{print $1}'
}
edit() {
    "$EDITOR" "$(get_file "$*")"
}
copy() {
    fzf_items "$*" | awk '{print $1}' | pbcopy
}
open() {
    fzf_items "$*" | awk '{print $1}' | xargs open
}
new() {
    printf "Name: "
    read -r
    RFILE="$(echo "$REPLY" | tr ' ' '-')"
    touch "$NOTES_FOLDER/$RFILE"
}
add() {
    RFILE="$(get_file)"
    if echo "$1" | grep -qE "^http"; then
        LINK="$1"
    elif echo "$(pbpaste)" | grep -qE "^http"; then
        LINK="$(pbpaste)"
    else
        echo "No link passed or found in clipboard" && exit 1
    fi
    grep -q "^$LINK" "$RFILE" && echo "$(tput setaf 1)[Already available]$(tput sgr0) $(pbpaste)" && exit 1
    echo "$RFILE < $(pbpaste)"
    printf "Comments(empty for none): "
    read -r
    if [ -n "$REPLY" ]; then
        echo "$(pbpaste) '$REPLY'" >>"$RFILE"
    else
        echo "$(pbpaste)" >>"$RFILE" # echo is kept is so that it inserts a newline
    fi
}
all() {
    find "$NOTES_FOLDER" -type f -depth 1 | while read -r file; do
        sed "s|$| #$(basename "$file")|" "$file"
    done |
        fzf -m --preview-window up:1 --preview 'echo {} | sed "s|^.[^ ]* ||"' |
        awk '{print $1}'
}

if [ -n "$1" ]; then
    OPTION="$1"
    shift
else
    OPTION="add"
fi
case "$OPTION" in
"list") list "$*" ;;
"print") get "$*" ;;
"copy") copy "$*" ;;
"open") open "$*" ;;
"new") new "$*" ;;
"add") add "$*" ;;
"all") all "$*" ;;
"edit") edit "$*" ;;
*) echo "Options are: list print copy open new add all" ;;
esac

note commit # commit changes
