#!/bin/sh

set -e

case "$1" in
"melpa") open "https://melpa.org/#/?q=$2" ;;
"github") open "https://github.com/search?q=$2" ;;
"npm") open "https://www.npmjs.com/search?q=$2" ;;
*) echo "Unknown search engine $1" && exit 1
esac
