#!/bin/sh

set -e

FILE="$1"
[ -z "$1" ] && echo "Using latest screenshot" \
    && FILE="$(\ls -Art -d ~/Documents/Screenshots/* | tail -n 1)" 

telegram_send() {
    case "$1" in
    *.png | *.jpg | *.JPG | *.jpeg | *.gif | *.webp) toi "$1" ;;
    *.mp4 | *.mkv | *.mov | *.avi | *.m4v | *.webm) tov "$1" "$2" ;;
    *) tof "$1" ;;
    esac
}

printf "Platform(t/s): "
read -r
case "$REPLY" in
    t*) telegram_send "$FILE" ;;
    s*) slacksend "$FILE" ;;
esac
