#!/bin/bash

set -e

cd "$HOME/Documents/Projects/projects/redirects"

URL="$1"
SUB="$2"

if [ -z "$URL" ]; then
    printf "Enter url: "
    read -r URL
fi

if [ -z "$SUB" ]; then
    printf "Enter shortpath: "
    read -r SUB
fi

echo "/$SUB $URL
$(cat _redirects)" | column -t > _redirects_new
mv _redirects_new _redirects

git add _redirects
git commit -m "Add $URL"
git push origin master

echo "links.meain.io/$SUB"
echo "links.meain.io/$SUB" | pbcopy || echo "Could not copy to clipboard"

cd -
