#!/bin/sh

# set -e

cd "$HOME/.config/emacs/straight/repos"
gloc 'git fetch' .
for folder in *;do
    pushd "$folder" > /dev/null
    gurl="$(git remote get-url origin|sed 's|.git$||;s|git@github.com:|https://github.com/|')"
    branch="$(git rev-parse --abbrev-ref HEAD)"
    count="$(git log master..origin/master 2>/dev/null |grep -c .)"
    if ! [ 0 = "$count" ]; then
        echo "# $folder ($count)"
        git log $branch..origin/$branch --oneline |
            sed "s|\([a-z0-9]*\) \(.*\)$|\1 \2 [view]($gurl/commit/\1)|"
        echo ""
    fi
    popd > /dev/null
done > /tmp/straight-available-updates.md
$EDITOR --no-wait /tmp/straight-available-updates.md
