#!/bin/sh

set -e

SESSION="$1"
if [ -z "$1" ]; then
    if [ -n "$(tmux ls)" ]; then
        if [ -n "$TMUX" ]; then
            FZF_DEFAULT_OPTS='
                -1 -0
                --prompt=" "
                --inline-info
                --color fg:242,hl:250,fg+:15,bg+:234,hl+:2
                --color info:108,prompt:242,spinner:108,pointer:1,marker:168
                ' SESSION=$(tmux ls |
                grep -v "$(tmux display-message -p "#S")" |
                sed 's/:.*//g' |
                fzf --prompt "Session: " --preview 'tmux-tree {}' --reverse --print-query |
                \tail -n1)
        else
            SESSION=$(tmux ls |
                sed 's/:.*//g' |
                fzf --prompt "Session: " --preview 'tmux-tree {}' --reverse --print-query |
                \tail -n1)
        fi
    fi
fi

if [ -n "$SESSION" ]; then
    tmuxsession "$SESSION"
fi
