#!/bin/sh

set -e

cleanup() {
    tput cnorm
}
trap cleanup EXIT
tput civis

# use `rc._forcecolor=on` for colors
if command -v watchexec; then
    watchexec -c -w "$HOME/.local/share/task" -w "$HOME/.taskrc" \
        "tput civis && task limit:$(($(tput lines) - 1)) $*|tail -n+4|sed '/^$/d'|perl -pe 'chomp if eof'"
else
    watch -c -d -t "task limit:100 $* | tail -n+4|sed '$ d'"
fi
