#!/bin/sh

set -e

TASK="$(task limit:100 $* 2>/dev/null | tail -n+4 | sed '$ d' |
	choose -f 'DankMono Nerd Font' -s 23 -m)"
if echo "$TASK" | grep -q '^\.'; then
	NEW_TASK="$(echo "$TASK" | sed 's|^\. *||')"
	sp $NEW_TASK
else
	TASK_ID="$(echo "$TASK" | cut -d' ' -f1)"
	task "$TASK_ID" done
fi
