#!/bin/sh

set -e

tasklist="$(task treview 2>/dev/null | tail -n+4 |
	grep -vE '^\d* tasks$' | grep -vE '^$' | grep -E '^ ? ? ?\d' |
	awk '{print $1}')"
for taskid in $tasklist; do
	clear
	task "$taskid" info 2>/dev/null
	while true; do
		printf "Review: "
		read -r
		if [ -n "$REPLY" ]; then
			task "$taskid" $REPLY || echo "Incomplete command"
		else
			break
		fi
	done
done
