#!/bin/sh

set -e

rust_project() {
    DIR="$(date '+%s')"
    mkdir -p "/tmp/temp-sessions/$DIR" && cd "/tmp/temp-sessions/$DIR"
    printf "Rust project name: "
    read -r
    cargo new "$REPLY"
    cd "$REPLY"
    tmuxsession "temp-$REPLY"
}

javascript_project() {
    DIR="$(date '+%s')"
    printf "Javascript project name: "
    read -r
    mkdir -p "/tmp/temp-sessions/$DIR/$REPLY" && cd "/tmp/temp-sessions/$DIR/$REPLY"
    npm init -y
    tmuxsession "temp-$REPLY"
}

quick_project() {
    DIR="$1"
    mkdir -p "/tmp/temp-sessions/$DIR" && cd "/tmp/temp-sessions/$DIR" &&
        tmuxsession "temp-$DIR"
}

if [ -n "$1" ]; then
    case "$1" in
    "rust") rust_project ;;
    "js"|"Javascript"|"npm") javascript_project ;;
    *) quick_project "$@" ;;
    esac
else
    DIR="$(date '+%s')"
    mkdir -p "/tmp/temp-sessions/$DIR" && cd "/tmp/temp-sessions/$DIR" &&
        tmuxsession "temp-$DIR"
fi
