#!/bin/sh

set -e

DIR="$(date '+%s')"
mkdir -p "/tmp/temp-sessions/$DIR"
cd "/tmp/temp-sessions/$DIR"

if [ -z "$1" ]; then
    GITURL=$(pbpaste)
elif echo "$1" | grep '/' > /dev/null; then
    GITURL="https://github.com/$1.git"
else
    GITURL="https://github.com/meain/$1.git"
fi

FOLDER="$(echo "$GITURL" | sed 's/.*\///g' | sed 's/\..*//g')"
if [ -n "$FOLDER" ];then
    git clone --depth 1 "$GITURL"
    cd "$FOLDER" || return 1
    tmuxsession "$FOLDER"
else
    tmuxsession "temp-$DIR"
fi




