#!/bin/sh

set -e

DIR="/Users/meain/Documents/Projects/others/clones"

cd "$DIR"

if [ -z "$1" ]; then
    GITURL=$(pbpaste)
elif echo "$1" | grep '/' > /dev/null; then
    GITURL="https://github.com/$1.git"
else
    GITURL="https://github.com/meain/$1.git"
fi

FOLDER="$(basename "$GITURL" | sed 's|.git$||')"
if [ -d "$FOLDER" ];then
    cd "$FOLDER" && git pull
else
    git clone --depth 1 "$GITURL"
    cd "$FOLDER" || return 1
fi

tmuxsession "$FOLDER"
