#!/bin/sh

set -e

cd ~/.notes/todo

if [ "$1" = "new" ];then
    printf "Name: "
    read -r
    [ -z "$REPLY" ] && exit 1
    echo "$REPLY.md" > /tmp/tk-file
    taskell "$HOME/.notes/todo/$REPLY.md"
elif [ "$1" = "todo" ];then
    taskell "$HOME/.notes/todo/todo-$(date +%d-%m-%Y).md"
elif [ "$1" = "f" ] || [ ! -f /tmp/tk-file ] ;then
    export FZF_DEFAULT_OPTS='
        -1 -0
        --prompt=" "
        --inline-info
        --color fg:-1,hl:4,fg+:1,bg+:-1,hl+:4
        --color info:108,prompt:242,spinner:108,pointer:1,marker:168
    '
    FILE="$(\ls -t | fzf --preview "cat ./{}")"
    [ -z "$FILE" ] && exit 0
    echo "$FILE" > /tmp/tk-file
    taskell "$FILE"
else
    taskell "$HOME/.notes/todo/$(cat /tmp/tk-file)"
fi

