#!/bin/sh

set -e

cd ~/.notes/todo

FZF_DEFAULT_OPTS='
            -1 -0
            --prompt=" "
            --reverse
            --inline-info
            --color fg:248,hl:250,fg+:232,bg+:231,hl+:2
            --color info:108,prompt:242,spinner:108,pointer:1,marker:168
' NAME="$(fzf --preview-window=up --preview "cat {}")"
[ -z "$NAME" ] && exit 0
taskell "$NAME"
git add . && git commit -m 'Update todo' >/dev/null
nohup git push origin master >/dev/null &
