#!/bin/sh

set -e

SESSION="$(echo "$1" | sed 's| |-|g')"

if [ -z "$TMUX" ]; then
    clear # imoprtant, do not remove
    tmux attach -t "$SESSION" || tmux new -s "$SESSION"
else
    tmux switch-client -t "$SESSION" || tmux -2 new-session -d -s "$SESSION" &&
        tmux switch-client -t "$SESSION"
fi

[ -n "$2" ] && tmux send -t "$SESSION" "$2" ENTER
