#!/bin/sh

set -e

SESSION="$1"

if [ -z "$TMUX" ];then
    tmux attach -t "$SESSION" || tmux new -s "$SESSION"
else 
    tmux switch-client -t "$SESSION" || tmux -2 new-session -d -s "$SESSION" && tmux switch-client -t "$SESSION"
fi
