#!/bin/sh

set -e

NOTES_FOLDER="$HOME/.notes"
mkdir -p "$NOTES_FOLDER/.trash"
TODO_FILE="$NOTES_FOLDER/todo"

push_upstream() {
    (cd "$NOTES_FOLDER" && git add . && git commit -m "Modify todo" >/dev/null && git push origin master) || exit 0
}

case "$1" in
l) grep -vE '^\s*x' "$TODO_FILE" | bat -l md ;;
*) "$EDITOR" "$TODO_FILE" && push_upstream ;;
esac
