#!/bin/sh

curl -X POST \
     -H 'Content-Type: application/json' \
     -d "{\"chat_id\": \"$TELEGRAM_USER_ID\", \"text\": \"$1\", \"disable_notification\": true}" \
     "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" >/dev/null 2>&1 && echo "Message sent"
