#!/bin/sh

set -e

TNAME="$(pwd|xargs basename)"
IGNORE_STRING=""
if [ -f .dockerignore ];then
    IGNORE_STRING="$(sed '/^\ *$/d;s|^|--exclude |' .dockerignore | tr '\n' ' ')"
fi
rsync -azvr --exclude '.git' $IGNORE_STRING . "$EXPERIMENT_VM:/tmp/$TNAME"
ssh "$EXPERIMENT_VM" "cd /tmp/$TNAME && docker build ."
