#!/bin/sh

set -e

PATH="$PATH:$HOME/.bin"
NAME="$(ts -o "$1" | xargs cat | grep -o '/Users/meain/Desktop/newsboat-downloads/.*' | xargs basename | xargs echo)"
if [ -n "$NAME" ];then
    osascript -e "display notification \"$NAME\" with title \"[TS] Download complete\""
else
    osascript -e "display notification \"$4\" with title \"[TS] Download comlete\""
fi
