#!/bin/sh

IGNORE_LIST=$(cat "$HOME"/.datafiles/ignored_mail_list| tr '\n' '|' | sed 's/|$//')
cat "$HOME"/.local/share/mail/meain/INBOX/new/* |
    grep -E '^(From|Subject):' |
    sed '$!N;s/\n/ /' |
    grep -E -v "$IGNORE_LIST" |
    grep -E -v '(=?utf-8?|=?UTF-8?)' |
    sed 's/From: \(.*\)\ <.*Subject: \(.*\)/- \2 (\1)/' |
    sed 's/Subject: \(.*\) From: \(.*\)\ <.*/- \1 (\2)/' | # if from and subject is other inverted
    sed 's/From: <\(.*\)\> .*Subject: \(.*\)/- \2 (\1)/' | # if no name avaiable
    sed 's/From: \(.*\)\ .*Subject: \(.*\)/- \2 (\1)/' # if no name avaiable, but email without <>
