#!/bin/sh

export NOTMUCH_CONFIG="$HOME/.config/notmuch/config"
/usr/local/bin/notmuch search tag:unread and tag:inbox and '-tag:nonotify' and '-tag:notified' |
    cut -d']' -f2- | sed 's/([^(]*)$//;s/^\ */- /'
