#!/bin/sh
# makes use of newsboat db to generate page
# cron entry: 5 * * * * unreadrsstopage > /tmp/rss.html

set -e

QUERY="
select
  rss_feed.title,
  rss_item.title,
  rss_item.url
from
  rss_feed
  cross join rss_item on rss_feed.rssurl = rss_item.feedurl
where
  rss_item.unread = 1
limit
  50
"

echo '<style>
tr:nth-child(even){background-color: #f2f2f2;}
tr:hover {background-color: #ddd;}
</style>'
echo '<table>'
items="$(sqlite3 --html  /Users/meain/.local/share/newsboat/cache.db "$QUERY" |
  sed -E 's|(https?://[^<]*)|<a targe="_blank" href="\1">\1</a>|')"
[ -z "$items" ] && echo "No unread articles" || echo "$items"
echo '</table>'
echo '<script>window.onload = () => {setInterval(() => {location.reload()}, 60000)}</script>'
