#!/bin/sh

_update_vim() {
    nvim +"let g:plug_window  = 'enew'" +PlugUpgrade +PlugUpdate +qall
}
_update_brew() {
    brew update
    brew upgrade
}
_update_rustup() {
    rustup update stable
    rustup update nightly
}
_update_dasht() {
    dasht-docsets-update
}
_update_repos() {
    gloc "git fetch" "$HOME/Documents/Projects/work/saama"
    gloc "git fetch" "$HOME/Documents/Projects/projects"
}
_update_gcloud() {
    gcloud components update -q
}
_update_bw() {
    eval "$(bw unlock | grep export | cut -d' ' -f2-)"
    bw sync
    bw lock
}

_update_helm() {
    helm repo update
}

_update_poetry() {
    poetry self update
}

case "$1" in
    vim) _update_vim ;;
    brew) _update_brew ;;
    rustup) _update_rustup ;;
    dasht) _update_dasht ;;
    repos) _update_repos ;;
    gcloud) _update_gcloud ;;
    bw) _update_bw ;;
    helm) _update_helm ;;
    poetry) _update_poetry ;;
    all)
        _update_vim
        _update_brew
        _update_rustup
        _update_dasht
        _update_repos
        _update_gcloud
        ;;
    allall)
        _update_vim
        _update_brew
        _update_rustup
        _update_dasht
        _update_repos
        _update_gcloud
        _update_helm
        _update_poetry
        ;;
    *)
        CANDIDATE="$(echo "all,allall,vim,brew,rustup,dasht,repos,bw,helm,poetry" | tr ',' '\n' | fzf)"
        [ -n "$CANDIDATE" ] && update "$CANDIDATE"
esac
