#!/bin/sh

set -e

_update_vim() {
    nvim +"let g:plug_window  = 'enew'" +PlugUpgrade +PlugUpdate +qall
}
_update_brew() {
    brew update
    brew upgrade
}
_update_rustup() {
    rustup update stable
    rustup update nightly
}
_update_dasht() {
    dasht-docsets-update
}
_update_repos() {
    gloc "git fetch" "$HOME/Documents/Projects/work/saama"
    gloc "git fetch" "$HOME/Documents/Projects/projects"
}
_update_gcloud() {
    gcloud components update -q
}
_update_bw() {
    bw sync
}

case "$1" in
    vim) _update_vim ;;
    brew) _update_brew ;;
    rustup) _update_rustup ;;
    dasht) _update_dasht ;;
    repos) _update_repos ;;
    gcloud) _update_gcloud ;;
    bw) _update_bw ;;
    all)
        _update_vim
        _update_brew
        _update_rustup
        _update_dasht
        _update_repos
        _update_gcloud
        _update_bw
        ;;
    *)
        update "$(echo "all,vim,brew,rustup,dasht,repos,bw" | tr ',' '\n' | fzf)"
esac
