#!/bin/sh

set -e

# 1 = Query string
# 2 = Default value
# 3 = Possible input from stdin
input="$3"
if [ -z "$3" ];then
    printf "%s(%s): " "$1" "$2" 1>&2
    read -r
    if [ -z "$REPLY" ]; then
        input="$2"
    else
        input="$REPLY"
    fi
fi
echo "$input"
