#! /bin/bash

source `which virtualenvwrapper.sh` 2> /dev/null

DEFAULT_VENV_PYTHON_VERSION=${DEFAULT_VENV_PYTHON_VERSION:-"3.6.6"}
PYENV_ROOT=${PYENV_ROOT:-"$HOME/.pyenv"}

# select from available versions
PYVERSION=$(pyenv versions | {
  echo "  Default ($DEFAULT_VENV_PYTHON_VERSION)"
  tail -n +2
  echo '  Other ( Install from pyenv )'
} | fzf --no-sort | sed 's/^ *//')
echo "PYVERSION" "$PYVERSION"


# install if not available
if [ "$PYVERSION" = 'Other ( Install from pyenv )' ]; then
  PYVERSION=
  # comm -23 <(pyenv install -l) <(pyenv versions)
  PYVERSION=$(pyenv install -l | tail -n +2 | fzf --no-sort | sed 's/^ *//')
  pyenv install "$PYVERSION"
elif [ "$PYVERSION" = "Default ($DEFAULT_VENV_PYTHON_VERSION)" ]; then
  PYVERSION=$DEFAULT_VENV_PYTHON_VERSION
  echo "PYVERSION" "$PYVERSION"
fi
PYNAME=$(readlink "$PYENV_ROOT/versions/$PYVERSION/bin/python")

if [ -n "$PYVERSION" ]; then
  if [ -z "$1" ]; then
    read -r -p "Name of virtualenv: " VIRTUALENVNAME
  else
    VIRTUALENVNAME=$1
  fi

  mkvirtualenv "$VIRTUALENVNAME" -p "$PYENV_ROOT/versions/$PYVERSION/bin/$PYNAME"
fi
