#!/bin/sh

set -e

mkdir -p /tmp/notes
if [ "$1" = "list" ]; then
    ls -t /tmp/notes | fzf --header "Select file" --preview "cat /tmp/notes/{}" | xargs $EDITOR
else
    $EDITOR "/tmp/notes/$(xxd -l2 -ps /dev/urandom)" "+set ft=$1"
fi
