#!/bin/sh

set -e

DIR="$HOME/.cache/vime"
mkdir -p "$DIR"
if [ "$1" = "list" ]; then
    ls -t "$DIR" | fzf --header "Select file" --preview "cat '$DIR/{}'" | xargs -I{} "$EDITOR" "$DIR/{}"
elif [ "$1" = "last" ]; then
    ls -t "$DIR" | head -n1 | xargs -I{} "$EDITOR" "$DIR/{}"
else
    $EDITOR "$DIR/$(xxd -l2 -ps /dev/urandom)" "+set ft=$1"
fi
