#!/bin/sh

set -e


cat ~/.config/nvim/init.vim > /tmp/init-backup
echo 'profile start /tmp/vimprofile.log
profile func *
profile file *
' > /tmp/init-temp
cat ~/.config/nvim/init.vim >> /tmp/init-temp
cat /tmp/init-temp > ~/.config/nvim/init.vim
nvim "$@" +q
cat /tmp/init-backup > ~/.config/nvim/init.vim
cat /tmp/vimprofile.log | grep -E '^(Total time:|SCRIPT)' | sed 'N;s/\n/ /' | grep -E '^SCRIPT' | awk '{print $5,$2}' | sort -r | less
