#!/usr/bin/env python3

import json
import yaml
import sys

if len(sys.argv) > 1:
    print(json.dumps(yaml.safe_load(open(sys.argv[1]).read())))
else:
    data = sys.stdin.readlines()
    print(json.dumps(yaml.safe_load('\n'.join(data))))
