#!/bin/sh

if [ -z "$1" ];then
    echo "Usage: ytmusicplayer <--resume|URL>"
fi

if [ ! "$1" = "--resume" ];then
    youtube-dl --get-id "$1" -i > /tmp/vids &
    YDL=$(echo $!)

    cleanup() {
    echo "Cleaning up stuff..."
    kill -9 "$YDL"
    }

    trap cleanup EXIT

    echo "Waiting for song list to populate..."
    sleep 30
fi

sed 's|^|https://youtube.com/watch?v=|' /tmp/vids | xargs mpv --no-video 
