#!/bin/bash

# Copy last commit hash to clipboard on commit
git log -1 --format=format:%h | pbcopy

# Show number of commit so far
	
green=`tput setaf 2`
reset=`tput sgr0`
echo -e "★ ${green}$(git rev-list --count HEAD) ${reset}commits so far"
